### ISSUE TITLE
question manifest.json

### ISSUE THREAD

**Issue by SwissalpS** [lite-xl/lite-xl-plugins#260]
I didn't see ``trimwhitespace`` in the list anymore, nor is it in the manifest.json

So I thought that because it is now shipped by default with lite-xl...
... but then ``settings`` and a bunch of languages are on the list here and ``settings`` is in the manifest.

To me it would make sense, that all plugins are in the manifest, so that users who deleted a default plugin can easily restore it with ``lpm``

Is ``trimwhitespace`` intentionally no longer in either and ``settings`` mistakenly still is or v.v. ?

**Comment by adamharrison** [comment]
`trimwhitespace` is now a core plugin; should be shipped with all versions of lite. Users can't really delete it, unless they explicitly go into the lite data folder and do so (just like if they were do go in and delete `docview.lua`, for example, that's not really a case we'd cover). I think it's assumed that if you have plugins bundled into the core, generally you shouldn't be deleting them unless you're sure what you're doing.

`settings` is in here because it's not a core plugin; it's only shipped as part of the addons package, which basically just contains a bunch of extra plugins by default.

**Comment by SwissalpS** [comment]
``docview.lua`` is not in the plugins directory, which users are told to access to install and remove plugins (when not using lpm). There is a difference there.

**Comment by adamharrison** [comment]
Users should generally not be using the core plugins directory to install/uninstall plugins; usually plugins should be placed in either the `user/plugins` directory, or the `~/.config/lite-xl/plugins` directory.

**Comment by SwissalpS** [comment]
Thanks, my mistake that I use portable builds then.

**Comment by adamharrison** [comment]
Yeah; if you're using purely portable builds then, convention would be to install it in `user` (not under `data`); the portable version of the user directory. If you create that folder in your lite folder, it'll override the normal user directory, and keep everything local to your portable install.

**Comment by SwissalpS** [comment]
Thanks.

Follow-up question: would having a ``portableLiteXL/user/`` also disable lite-xl from reading the ``~/.config/lite-xl/`` config? I ask because I had to add a version check in there so that newer versions don't load settings for older versions. (and fail)

**Comment by adamharrison** [comment]
Yes; it fully overrides the `USERDIR` variable, so won't load anything from `~/.config/lite-xl` if you have `user`.

**Comment by SwissalpS** [comment]
note to self: have builder script make ``user`` when building portable variant
